#!/usr/bin/perl
use strict;
# Run a cgi script, and strip off the content-type

if( $0 =~ m:/[^/]*$: ) {  push @INC, $` }
require 'wkn_define.pl';


unless(@ARGV) { print "Usage: cgitohtml SCRIPT ARGS\n"; exit(1); }

open(SCRIPT, "-|") || exec @ARGV;
#open(SCRIPT, "-|") || exec "perl", "-T", @ARGV;
if(0){
   print "Failed to run script: @ARGV\n";
   exit(1);
}

unless(<SCRIPT> =~ m%^Content-type: text/html$%i and <SCRIPT> =~ m:^$: )
{
   print STDERR "Not a cgi script: $wkn::define::gen_index_script\n";
   print STDERR "Offending line: $_\n";
   close(SCRIPT);
   exit(1);
}

my $line;
while(defined($line = <SCRIPT>))
{
   #prefix relative paths with the cgi path
   $line =~ s#\b(href=\"|src=\")(?!http://|ftp://|/)#$1$wkn::define::cgi_wpath/$2#gi;
   print $line;
}
close(SCRIPT);

sub single_quote
{
   my(@out);
   foreach(@_)
   {
      push(@out, "\'$_\'");
   }
   return @out;
}
