#!/usr/bin/perl
use strict;
# Run a cgi script, and strip off the content-type

unless(@ARGV > 1) { print "Usage: cgitohtml SCRIPT_WEBPATH SCRIPT_PATH ARGS\n"; exit(1); }

my $cgi_wpath = shift(@ARGV);
open(SCRIPT, "-|") || exec @ARGV;
#open(SCRIPT, "-|") || exec "perl", "-T", @ARGV;
if(0){
   print "Failed to run script: @ARGV\n";
   exit(1);
}

unless(<SCRIPT> =~ m%^Content-type: text/html$%i and <SCRIPT> =~ m:^$: )
{
   print STDERR "Not a cgi script.\n";
   print STDERR "Offending line: $_\n";
   close(SCRIPT);
   exit(1);
}

my $line;
while(defined($line = <SCRIPT>))
{
   #prefix relative paths with the cgi path
   $line =~ s#\b(action=\"|href=\"|src=\")(?![^/]+:|/)#$1$cgi_wpath/$2#gi;
   print $line;
}
close(SCRIPT);

sub single_quote
{
   my(@out);
   foreach(@_)
   {
      push(@out, "\'$_\'");
   }
   return @out;
}
