#!/usr/bin/perl
#shows all use filedb, view and auth definitions and library calls in the given files

for $file (@ARGV)
{
   if(open(FILE, $file))
   {
	while($line = <FILE>)
        {
           while($line=~ m#((filedb|auth|view)[\w:]*)::(\w+)#)
           {
             $defines{$1}->{$3} = 1;
             $line = $';
           }
        }
      
      close(FILE);
   }
}
for $ns (sort keys %defines)
{
    print "Name Space: $ns\n";
    for $d (sort keys %{$defines{$ns}})
    {
       print "   $d\n";
    }
}
